---
repository:
  auto_init: true
  # security_and_analysis:
  #   advanced_security:
  #     status: enabled
  #   secret_scanning:
  #     status: enabled
  #   secret_scanning_push_protection:
  #     status: enabled
  has_issues: true
  has_projects: false
  has_wiki: false
  is_template: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  allow_auto_merge: true
  delete_branch_on_merge: true
  allow_update_branch: true
  squash_merge_commit_title: PR_TITLE
  squash_merge_commit_message: COMMIT_MESSAGES
  archived: false
  # allow_forking: false
  web_commit_signoff_required: false
  security:
    enableVulnerabilityAlerts: true
    enableAutomatedSecurityFixes: true
